# Generated by Django 4.2.7 on 2023-11-16 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_descripcion',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Coordinador', 'Coordinador'), ('Docente', 'Docente')], max_length=20, unique=True),
        ),
    ]
