# Generated by Django 4.2.7 on 2023-11-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_usuario_login_alter_rol_rol_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='eva_sugerencias',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='eva_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
