# Generated by Django 4.2.7 on 2023-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_evaluacion_eva_sugerencias_alter_evaluacion_eva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol_descripcion',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Coordinador', 'Coordinador'), ('Planta', 'Planta'), ('TC', 'TC'), ('Catedra', 'Catedra')], max_length=20, unique=True),
        ),
    ]
