# Generated by Django 4.2.7 on 2023-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_rol_rol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='eva_estado',
            field=models.CharField(choices=[('E', 'En ejecución'), ('T', 'Terminado'), ('S', 'Suspendido')], max_length=1),
        ),
    ]
