# Generated by Django 4.2.7 on 2023-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_alter_evaluacion_eva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usu_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro - No mencionar')], max_length=1),
        ),
    ]
