# Generated by Django 4.2.7 on 2023-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_alter_usuario_usu_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
